collections:
  - name: community.kubernetes
    version: 1.2.0
  - name: community.aws
    version: 1.4.0
  - name: community.crypto
    version: 1.6.0
roles:
  - name: kameshsampath.rosa_demos
    src: https://github.com/kameshsampath/ansible-role-rosa-demos
    version: master
    
