---
- name: ROSA with Customer OIDC Provider
  hosts: localhost
  connection: local

  vars:
    rollback: false
    oidc: True

  vars_prompt:
    - name: aws_access_key
      prompt: Enter AWS Access Key

    - name: aws_secret_key
      prompt: Enter AWS Secret Key

  roles:
    - kameshsampath.rosa_demos